### ISSUE TITLE
Support tab completion for remote/local path

### ISSUE THREAD

**Issue by pengsrc** [yunify/qsctl#29]
Support tab completion for remote and local path should be easier to use.

``` bash
# Example

$ qsctl ls qs://bucket-name/na

# Press Tab

$ qsctl ls qs://bucket-name/name/

# Press Tab Tab

$ qsctl ls qs://bucket-name/name/
LiLei  HanMeimei
```

Except for `ls`, other commands like `cp`, `mv` and `sync` could support this behavior.

**Comment by Xuanwo** [comment]
Supported by PR https://github.com/yunify/qsctl/pull/55 .
