### ISSUE TITLE
test failed with http 400

### ISSUE THREAD

**Issue by wangzw** [yunify/qsctl#3]
the error reason is `max_requests_exceeded`
`max_requests_exceeded  当请求创建和删除 bucket 过于频繁时，返回该错误   400`

Please reuse the bucket instead of recreate bucket for every test cases.

**Comment by wangzw** [comment]
It's better to do mock test instead of create real object on QingStor

**Comment by prettyxw** [comment]
> Please reuse the bucket instead of recreate bucket for every test cases.

Yes, we should reuse the bucket in tests.


> It's better to do mock test instead of create real object on QingStor

Mock test is not reliable for tests that depend on online service. We are running this tests in our staging environment, so it's harmless. And the bucket name "validbucket" will be replaced with an unique one.

**Comment by wangzw** [comment]
hardcode a bucket name may bring trouble for contributors if "validbucket" is ready created.

**Comment by osier** [comment]
It's mistake. We should mock the tests instead, will fix it. Thanks for reporting.
