### ISSUE TITLE
support upload data to QingStor from stdin

### ISSUE THREAD

**Issue by wangzw** [yunify/qsctl#4]
it is a convenient feature to upload data to QingStor from stdin. We can pipeline data from upstream command and upload data to QingStor without write to local disk. 

`some_command_generate_lot_data | gzip |  qsctl cp - qs://some_bucket/some_key`

**Comment by osier** [comment]
Reasonable, accepted.

**Comment by Xuanwo** [comment]
Supported by https://github.com/yunify/qsctl/pull/5 , thx @wangzw
