### ISSUE TITLE
qsctl support rsync 

### ISSUE THREAD

**Issue by martinyunify** [yunify/qsctl#59]
rsync is a popular utility that is used for synchronizing files.
https://en.wikipedia.org/wiki/Rsync
I'm wondering if we can extend qsctl to synchronize files from a remote server which supports rsync protocol. 

One scenario would be: linux repository synchronization

**Comment by Xuanwo** [comment]
`a remote server` here means what ? `QingStor Server` or just a `Linux server with rsyncd` ?

### For QingStor Server

It's obvious that qingstor will not support rsyncd for now, so qsctl can't support this.

### For Linux server with rsyncd

qsctl is a unix like tools for user to use qingstor, and`rsync` is not the thing that qsctl should do. And you can use `rsync` directly.

To summarise, we will not support this feature.

**Comment by martinyunify** [comment]
I mean the user can sync files from file server which supports rsync protocol without downloading all of the artifacts. And rsync can work with ssh to copy files between two linux hosts. It is a powerful utility and is widely used in unix world.  I think it is a de-fecto standard way to sync files between unix hosts.

**Comment by Xuanwo** [comment]
I did agree with you that `rsync` is very uesful, but it doesn't mean we should do it by `qsctl`.

First of all, qsctl just did work between `QingStor Server` and `Local`, and `rsync` is not in the map.
Then, qsctl is tool for all platform, we should also take `windows`, `darwin` into consideration.

In a word, I don't think we should do this job in qsctl, and I will be happy to discuss how to sync files in other ways.

**Comment by martinyunify** [comment]
rsync works under windows. And adopting rsync doesn't mean just invoking rsync directly. There are a few rsync protocol implementations available.  And I think this utility should support different datasource because the general process of moving data from/to qingstor can be reused although there are a lot of implementation details in different protocols.

**Comment by Xuanwo** [comment]
Closed for not implement in qsctl and use another method instead.
