### ISSUE TITLE
qsctl copy get wrong object content

### ISSUE THREAD

**Issue by wangzw** [yunify/qsctl#63]
I copy 12254 small files from a bucket to local filesystem. The total data is 534.05 MB.

```
qsctl cp --no-progress -r qs://xxx/ /local/path/
```

The command exit with exit code 0.

I got wrong content for some files, which is not consistent with the object content in qingstor bucket.

```
[root@i-ds1xio2d ~]# python --version
Python 2.7.5
[root@i-ds1xio2d ~]# qsctl -v
qsctl 1.7.2
[root@i-ds1xio2d ~]# uname -a
Linux i-ds1xio2d 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@i-ds1xio2d ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by Xuanwo** [comment]
I'll have a test on this.

**Comment by Xuanwo** [comment]
Maybe related to this commit: https://github.com/yunify/qsctl/commit/f071667b12f8172451a9e7d63dcdd44f9348bf22

Do your files have illegal file names? And can you upgrade to 1.7.3 to have an another test?

**Comment by wangzw** [comment]
send you bucket id in qingcloud ticket

**Comment by wangzw** [comment]
The latest version in pypi is 1.7.2

**Comment by wangzw** [comment]
```
aws s3 cp --endpoint-url 'https://s3.pek3a.qingstor.com' --recursive qs://xxx/ /local/path/
```

get correct object content

**Comment by Xuanwo** [comment]
Yes, I'm sure there is a bug related to multi thread, I will fix it.

`qsctl cp --no-progress -r qs://xxx/ /local/path/ --worker 1` is a workaround.

**Comment by Xuanwo** [comment]
It's a SDK bug: https://github.com/yunify/qingstor-sdk-python/blob/master/qingstor/sdk/service/bucket.py#L813

We will fix & release it tomorrow.

**Comment by Xuanwo** [comment]
And this will also lead to files missing: https://github.com/yunify/qsctl/blob/master/qingstor/qsctl/commands/base.py#L157-L166 , patch is coming.

**Comment by Xuanwo** [comment]
@wangzw This release https://github.com/yunify/qsctl/releases/tag/1.7.4 should fix this bug.

**Comment by Xuanwo** [comment]
Closed for fixed.
