### ISSUE TITLE
Failed to upload larger file

### ISSUE THREAD

**Issue by wangzw** [yunify/qsctl#66]
<img width="817" alt="screen shot 2017-12-07 at 18 46 43" src="https://user-images.githubusercontent.com/1254826/33711460-09f51de0-db7f-11e7-8d18-55a72bff41c3.png">

The file is about 60GB

**Comment by Xuanwo** [comment]
Our progress bar used int, and 60GB is too big for it. We will fix it soon.

**Comment by wangzw** [comment]
Has this issue been fixed?

**Comment by Xuanwo** [comment]
This should be fixed on windows.
