### ISSUE TITLE
where is the logfile of qsctl

### ISSUE THREAD

**Issue by jerryjedi** [yunify/qsctl#69]
After installed qsctl and setup the config in the config.yaml as follow：
![image](https://user-images.githubusercontent.com/7875026/45935344-30ab2400-bfdd-11e8-9562-b37e333c4894.png)
Then try to use "qsctl ls qs://bucket-name", but failed. The error message is "Error: Please check if bucket <slx-public> exists. If you are trying to create a bucket, please specify the zone name.". Where is the logfile and how can I do the debug?

**Comment by Xuanwo** [comment]
Your host should be `qingstor.com` instead of `sh1a.qingstor.com`, and qsctl only print message to stdout.

**Comment by jerryjedi** [comment]
got, now is ok! Thanks.
