### ISSUE TITLE
qsctl mb should set flag "zone" required

### ISSUE THREAD

**Issue by Prnyself** [yunify/qsctl#76]
Executing qsctl mb command with only bucket-name will get 403 permission denied. 
`qsctl mb test-bucket`
And adding "zone" flag to specify which zone to create bucket works.
`qsctl mb test-bucket -z sh1a`

**Comment by Xuanwo** [comment]
Fix in https://github.com/yunify/qsctl/pull/78 ?

**Comment by Prnyself** [comment]
> Fix in #78 ?

Yes, it fix temporally, and will be refactored soon.
